name: e2e hardhat tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  run_e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfile
          load: true
          tags: ${{ application_name }}:latest
          cache-from: type=gha
          cache-to: type=gha

      - name: Run container
        run: |
          docker run -d -p 8080:8080 \
          --name ${{ application_name }} ${{ application_name }}:latest
      
      - name: Run Newman
        run: |
          newman run tests/e2e/e2e.postman_collection.json
